# Generated by Django 3.0.7 on 2020-06-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YaraRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rules')),
            ],
        ),
        migrations.DeleteModel(
            name='YaraRule',
        ),
    ]
