# Generated by Django 3.0.7 on 2020-06-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManager', '0002_auto_20200621_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yararulemodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
