# Generated by Django 3.0.7 on 2020-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManager', '0003_auto_20200621_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yararulemodel',
            name='file',
        ),
        migrations.AddField(
            model_name='yararulemodel',
            name='path',
            field=models.FilePathField(default='rules', path='./ruleManager/rules/'),
            preserve_default=False,
        ),
    ]
