# Generated by Django 3.0.7 on 2020-06-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManager', '0005_rulestagsmodel_tagmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulestagsmodel',
            old_name='path',
            new_name='idRule',
        ),
        migrations.RenameField(
            model_name='rulestagsmodel',
            old_name='tag',
            new_name='idTag',
        ),
    ]
