# Generated by Django 3.0.7 on 2020-06-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManager', '0006_auto_20200622_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rulestagsmodel',
            old_name='idRule',
            new_name='rule',
        ),
        migrations.RenameField(
            model_name='rulestagsmodel',
            old_name='idTag',
            new_name='tag',
        ),
    ]
